services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: bash -c "sleep infinity"
